### ISSUE TITLE
Improved Repo and Chart Inclusion

### ISSUE THREAD

**Issue by Dattax** [jfrog/chartcenter#3]
Currently, ChartCenter supports including new charts by making a pull request to a repos.yaml file and providing us the name, the source url of your repositories, and your name and email as the maintainer. The domain of this source url must match your email address so that we can verify that you are the owner of the repo and chart. 

**Proposal to Discuss:**

The goal of this issue is to discuss standardization of the inclusion process. This should help ChartCenter and other chart repositories ingest HelmCharts in ways that support the community - and should be a shared exercise that other community members also use and endorse. 

**Details:**

Moving forward, we hope to be able to support other ways to include charts in ChartCenter:
* Push from source (how is ownership verified)
* Login with GitHub and to authenticate ownership and push directly
* Login with Bitbucket and to authenticate ownership and push directly
* Login with GitLab and to authenticate ownership and push directly

**Issues with Repos/Versioning**
* Chart versioning isn’t standardized. We need standards to version new charts so we can find them in repos automatically 
Folder Path

**See Issue with [Reserving Namespaces](https://github.com/jfrog/chartcenter/issues/4)**
* Namespaces must be unique
* If we allow push from source, how do we keep namespace reservations safe from abuse? (We should allow organizations to reserve their namespaces)

**Issues / Questions:**
* If a chart fails validation - how should maintainers be informed?
* Checking ownership of the Helm repo may be different based on the different inclusion type we support. 
* License and legal compliance - what licenses should we automatically clear and will they include language for redistribution?

**Comment by ankushchadha** [comment]
Closing the issue since the feature was rolled out last week. Great work @elioengcomp, @aarvyved, @rimusz, and @Dattax.

Information about this feature is located at https://chartcenter.io/docs/source-inclusion.html
